# -*- coding: utf-8 -*-
"""project1.1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ra2zJokUlr_Uq_v5csIaJC1JZYxRJ_CQ
"""

filename=input("Input the filename")
f_extns= filename.split(".")
print("the extension of file is:"+str(f_extns[-1]))